### ISSUE TITLE
How should I use this module in `development` vs. `production`

### ISSUE THREAD

**Issue by serapath** [AgentME/ud#3]
`ud` and `browserify-hmr` work very nice while developing. As soon as I deploy to production I don't use the hmr feature anymore, so the code should built without `ud`. Is there a browserify-transform or an option that get's rid of everything "ud" related in the client code?

**Comment by leesei** [comment]
See #2

**Comment by AgentME** [comment]
`ud/noop` has been added as a minimal hmr-less and dependency-free implementation of ud's functions, and a section has been added to the readme about it.

**Comment by serapath** [comment]
thx :-)
