### ISSUE TITLE
Function is executed multiple times

### ISSUE THREAD

**Issue by serapath** [AgentME/ud#4]
**Bug?**
When I open the stuff below in my browser, without changing any file, some of my code is already executed twice.  
What happens here?

# Given
* `index.html`
```html
<body><script src="bundle.js"></script></body>
```
* `index.js`
```js
var h = require('virtual-dom/h')
var main = require('main-loop')
var ud = require('ud')
var counter = 0
var render = ud.defn(module, function render (state) {
  console.log('LOGGING: ' + counter++)
  return h('div', [
    h('h1', 'clicked ' + state.n + ' times'),
    h('button', { onclick: onclick }, 'click me!')
  ])
  function onclick () {
    loop.update({ n: state.n + 1 })
  }
})
var loop = ud.defonce(module, function () {
  var loop = main({ n: 0 }, render, require('virtual-dom'))
  document.body.appendChild(loop.target)
  return loop
})
loop.update(loop.state)
```

# When
```bash
watchify index.js -p [ browserify-hmr -u http://$(my-local-ip):3123 -h 0.0.0.0 ] -o bundle.js -dv
```

# Then
```bash
[HMR] Attempting websocket connection to http://192.168.2.179:3123
LOGGING: 0
LOGGING: 1
```

**Comment by AgentME** [comment]
I think your code is just calling the render function twice. See if the issue still happens when you don't use `ud.defn`. (Replace `ud.defn(module, ` with `(` in your code.)

**Comment by AgentME** [comment]
I was able to run your code locally. When I took out all of the ud usage (and browserify-hmr too just for completeness), it still logged the same "LOGGING:" messages.

I'm not very familiar with the main-loop module, but I assume it calls render once when you first instantiate `loop`, and then render is called again when you run `loop.update`.

**Comment by AgentME** [comment]
Just an FYI: every time you edit index.js, the file will be re-executed. Your usage of ud is correct, except that each time you edit the file, the new execution will have a brand new `counter` variable initialized to 0. If you want to avoid that and persist the same counter value through all module replacements, you should use `ud.defonce` (with the `key` parameter because you're already using defonce below) to create a mutable object that has a `counter` property:

```js
var h = require('virtual-dom/h')
var main = require('main-loop')
var ud = require('ud')
var persistent = ud.defonce(module, () => ({counter: 0}), 'persistent');
var render = ud.defn(module, function render (state) {
  console.log('LOGGING: ' + persistent.counter++)
  return h('div', [
    h('h1', 'clicked ' + state.n + ' times'),
    h('button', { onclick: onclick }, 'click me!')
  ])
  function onclick () {
    loop.update({ n: state.n + 1 })
  }
})
var loop = ud.defonce(module, function () {
  var loop = main({ n: 0 }, render, require('virtual-dom'))
  document.body.appendChild(loop.target)
  return loop
})
loop.update(loop.state)
```
