### ISSUE TITLE
Cannot use `import` on ud when running through Babel

### ISSUE THREAD

**Issue by manovotny** [AgentME/ud#5]
To be up front, I am not sure what is causing this. It could also be user error. :frowning: 

I do know that ud's generated `js/index.js` has the following code in it (at least I assume it's generated based on seeing `src` here on the repo).

```js
exports.markReloadable = markReloadable;
exports.defonce = defonce;
exports.defobj = defobj;
exports.defn = defn;
```

And when I try and use `import ud from 'ud'`, it produces the following console error when run through Babel. 

```
Uncaught TypeError: Cannot read property 'defn' of undefined
```

However, if I change the code mentioned above to this...

```js
module.exports = {
    markReloadable: markReloadable,
    defonce: defonce,
    defobj: defobj,
    defn: defn
};
```

...using `import ud from 'ud'` works as expected and without error.

Perhaps it's something with the use of Flow, but I am fairly inexperienced with it, so I am by no means placing any blame. Simply mentioning it.

As a work around, I can just use `const ud = require('ud')` and that works too. I would just like to use `import` along with the other libs I'm using.

**Comment by AgentME** [comment]
ud is written as an ES6 module and has no default export. The behavior you're seeing is intended, but I admit the documentation doesn't mention anything about it, and it's not (yet?) common for libraries to be ES6 modules.

You can import specific functions from ud:

```js
import {defn} from 'ud';
```

Or import all of the exports as an object:

```js
import * as ud from 'ud';
```

(With Babel, when you use `require` to load an ES6 module, the require call does the equivalent of the above `import *` statement if the module has any non-default exports.)

**Comment by manovotny** [comment]
Sorry I didn't think of selective or `*` import options. Thank you for being kind with your suggestions.

You're right. Both `import {defn} from 'ud'` and `import * as ud from 'ud'` work just fine too, which is perfectly acceptable to me.
