### ISSUE TITLE
Usage of defn without extending

### ISSUE THREAD

**Issue by oncletom** [AgentME/ud#7]
Hello,

I am trying to explain how HMR works but when I do this, and then change a prop inside the `button-count.jsx` file, both components are refreshed – one keeps its props (the second one) and the first one state is reseted. I was expecting it not to be updated at all.

```js
import { createElement } from 'react';
import ReactDOM from 'react-dom';
import ButtonCount from './button-count.jsx';
import {defn} from 'ud';

ReactDOM.render(
  createElement(ButtonCount),
  document.querySelector('#app')
);

ReactDOM.render(
  createElement(defn(module, ButtonCount)),
  document.querySelector('#app-hmr')
);
```

Is there any chance to avoid this side effect or am I doing something wrong?

Thanks a lot, it is by far the easiest HMR integration I have seen so far.

**Comment by AgentME** [comment]
HMR works by re-executing the edited file. ud is used to update or retrieve some values from the first run of the file.

Each time you edit button-count.jsx, button-count.jsx and this file are re-executed. The first render call references the ButtonCount class directly; each re-execution refers to a brand new class as far as React knows, so React doesn't try to persist the state. The second call using defn always refers to the original (defn wrapper around) ButtonCount (and defn does some magic to update the class), so React receives the same class on each render and knows to keep the state.

However, even if you always use defn like you did in the second render call here, you can still run into issues: any subcomponents will get a new identity on every re-execution and lose their state too. Also the entire tree will be re-rendered for a change in any component. I recommend using https://github.com/gaearon/react-transform-hmr (or whatever is marked as having replaced it by now, but I haven't personally tried that out yet) for React hmr needs as it doesn't have those problems and doesn't need changes made to the source code to work. ud can still be used in the same project for non-react modules.

**Comment by oncletom** [comment]
@AgentME awesome! That's very clear and thanks so much for taking the time to share it 😃
