### ISSUE TITLE
Support for ES6 classes?

### ISSUE THREAD

**Issue by steadicat** [AgentME/ud#8]
`defn` seems to be incompatible with native ES6 classes.

The docs say: “you can pass a class constructor to defn and have its methods be kept up to date.”

And the tests seem to test passing a `class` to `defn`: https://github.com/AgentME/ud/blob/d88e82ea08efdf8d7c604a2a9bf9d1fc82ff237e/test/index.js#L212

However, assigning to the prototype of an ES6 class is not allowed.

In Chrome, I get this error:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/6031/40457506-aaabd562-5eab-11e8-9fc9-0a5f0f2b5e3e.png">

**Comment by AgentME** [comment]
Thanks for the report. Apparently I'd only tested this transpiled classes, and never with native ones. I'll address this issue and #9.

**Comment by AgentME** [comment]
Fixed in 3.2.0.
