### ISSUE TITLE
Support for ES6 arrow functions?

### ISSUE THREAD

**Issue by steadicat** [AgentME/ud#9]
ES6 arrow functions don’t have a prototype:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/6031/40457925-0297cedc-5eae-11e8-9c8e-2b7a5c3c362e.png">

https://github.com/AgentME/ud/blob/34c4300f746a8b26cf4ac8137896946506bcdffe/src/index.js#L110

**Comment by AgentME** [comment]
Fixed in 3.1.2.
